# -*- coding: utf-8 -*-
"""movie recommender .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdHxEJRvySA74M3nGgRq9o9UEbBVi5UJ
"""

from pathlib import Path

import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
MOVIES_CSV = BASE_DIR / "tmdb_5000_movies.csv"
CREDITS_CSV = BASE_DIR / "tmdb_5000_credits.csv"
ENABLE_STEMMING = False


def resolve_csv(path: Path, expected_name: str) -> Path:
  if path.is_dir():
    candidate = path / expected_name
    if candidate.exists():
      return candidate
    matches = sorted(path.glob("*.csv"))
    if matches:
      return matches[0]
  return path


MOVIES_CSV = resolve_csv(MOVIES_CSV, "tmdb_5000_movies.csv")
CREDITS_CSV = resolve_csv(CREDITS_CSV, "tmdb_5000_credits.csv")

if not MOVIES_CSV.exists():
  raise FileNotFoundError(
    f"Missing {MOVIES_CSV}. Place tmdb_5000_movies.csv in the project folder."
  )
if not CREDITS_CSV.exists():
  raise FileNotFoundError(
    f"Missing {CREDITS_CSV}. Place tmdb_5000_credits.csv in the project folder."
  )

movies = pd.read_csv(MOVIES_CSV)
credits = pd.read_csv(CREDITS_CSV)

movies = movies.merge(credits, on='title')

# genre
# id
# keywords
#title
#overview
#cast
#crew

movies = movies[['movie_id','genres','title','overview','keywords','cast','crew']]

movies.isnull().sum()  #finding missing values

movies.dropna(inplace=True) #dropna() drop rows with null values inplace=True  modify the original dataframe directly (no new copy is created)

movies.duplicated().sum()  #finding any duplicate values

movies.iloc[0].genres  #prints first row of genre by index

import ast

# convert weird format into an actual list
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

movies['genres']=movies['genres'].apply(convert)

movies['keywords']=movies['keywords'].apply(convert)

#we want 3 main cast only
def convert3(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter!=3:
      L.append(i['name'])
      counter+=1
    else:
      break

  return L

movies['cast']=movies['cast'].apply(convert3)

movies.head()

def fetch_director(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break

  return L

movies['crew']=movies['crew'].apply(fetch_director)

movies['overview']= movies['overview'].apply(lambda x:x.split()) #converting into separated words

#removing spaces between words for tags
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

new_df=movies[['movie_id','title','tags']]

#convert tags into string again
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

#lowercase
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

new_df.head()

#to convert strings into vector form algorithm is k nearest neighbours for predicting similar movies later
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

vectors= cv.fit_transform(new_df['tags']).toarray()

cv.get_feature_names_out()

#stemming apply uses one word for similar words like loving loved love
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

ps.stem('loving')

def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

if ENABLE_STEMMING:
  new_df['tags']=new_df['tags'].apply(stem)

from sklearn.metrics.pairwise import cosine_similarity

#cosine distance angle
similarity=cosine_similarity(vectors)

sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

def recommend(movie):
  movie_index= new_df[new_df['title']==movie].index[0]
  distances = similarity[movie_index]
  movies_list= sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

import pickle

with open(BASE_DIR / 'movies.pkl', 'wb') as handle:
  pickle.dump(new_df, handle)

with open(BASE_DIR / 'similarity.pkl', 'wb') as handle:
  pickle.dump(similarity, handle)